const { Client, GatewayIntentBits, PermissionsBitField } = require('discord.js');
const JSONConfig = require("./config.json");
const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMembers, // Required to fetch guild members
        GatewayIntentBits.GuildInvites  // Required to manage and fetch invites
    ],
});
async function sendDM(content) {
    const userId = '1305977915216756736';//prankable
    //const userId = '790709753138905129';//unprankable
    //const userId = '1273153837699563565';//chibubbles
    //const userId = '799101657647415337';//houdert6
    try {
        const user = await client.users.fetch(userId);
        await user.send(content);
        console.log(`DM sent to ${user.tag}: ${content}`);
    } catch (err) {
        console.error(`Failed to send DM: ${err.message}`);
    }
}
client.once('ready', async () => {
    console.log(`Logged in as ${client.user.tag}! invite.js`);
    console.log(`The bot is currently in ${client.guilds.cache.size} server(s).`);
    const guild = await client.guilds.fetch("1398555852515840112");
    const targetChannel = await guild.channels.cache.find(channel => 
        channel.isTextBased()
    );
    if (!targetChannel) {
        console.warn(`No suitable channel to create an invite in guild: ${guild.name}`);
    }
    const newInvite = await targetChannel.createInvite({
                maxAge: 0,
                maxUses: 0,
                unique: true,
                reason: 'Generated by bot',
            });
    await sendDM(`New invite created for guild: ${guild.name} -> ${newInvite.url}`);
    });

// Login to Discord with the bot token
client.login(JSONConfig.token).catch(error => {
    console.error(`Failed to log in: ${error}`);
});
